### YamlMime:ManagedReference
items:
- uid: System.Data.Linq.DuplicateKeyException
  id: DuplicateKeyException
  children:
  - System.Data.Linq.DuplicateKeyException.#ctor(System.Object)
  - System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String)
  - System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String,System.Exception)
  - System.Data.Linq.DuplicateKeyException.Object
  langs:
  - csharp
  name: DuplicateKeyException
  nameWithType: DuplicateKeyException
  fullName: System.Data.Linq.DuplicateKeyException
  type: Class
  summary: "Generata quando viene effettuato un tentativo di aggiungere un oggetto alla cache delle identità tramite una chiave che è già in uso."
  syntax:
    content: 'public class DuplicateKeyException : InvalidOperationException'
  inheritance:
  - System.InvalidOperationException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object)
  id: '#ctor(System.Object)'
  parent: System.Data.Linq.DuplicateKeyException
  langs:
  - csharp
  name: DuplicateKeyException(Object)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Data.Linq.DuplicateKeyException&quot;> </xref> classe."
  syntax:
    content: public DuplicateKeyException (object duplicate);
    parameters:
    - id: duplicate
      type: System.Object
      description: "La chiave duplicata che ha causato la generazione dell&quot;eccezione."
  overload: System.Data.Linq.DuplicateKeyException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String)
  id: '#ctor(System.Object,System.String)'
  parent: System.Data.Linq.DuplicateKeyException
  langs:
  - csharp
  name: DuplicateKeyException(Object,String)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Data.Linq.DuplicateKeyException&quot;> </xref> classe facendo riferimento alla chiave duplicata e fornendo un messaggio di errore."
  syntax:
    content: public DuplicateKeyException (object duplicate, string message);
    parameters:
    - id: duplicate
      type: System.Object
      description: "La chiave duplicata che ha causato la generazione dell&quot;eccezione."
    - id: message
      type: System.String
      description: "Il messaggio da visualizzare quando viene generata l&quot;eccezione."
  overload: System.Data.Linq.DuplicateKeyException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String,System.Exception)
  id: '#ctor(System.Object,System.String,System.Exception)'
  parent: System.Data.Linq.DuplicateKeyException
  langs:
  - csharp
  name: DuplicateKeyException(Object,String,Exception)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String,Exception)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String,Exception)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.Data.Linq.DuplicateKeyException&quot;> </xref> classe fa riferimento la chiave duplicata, fornendo un messaggio di errore e specificando l&quot;eccezione che ha causato questa eccezione viene generata."
  syntax:
    content: public DuplicateKeyException (object duplicate, string message, Exception innerException);
    parameters:
    - id: duplicate
      type: System.Object
      description: "La chiave duplicata che ha causato la generazione dell&quot;eccezione."
    - id: message
      type: System.String
      description: "Il messaggio da visualizzare quando viene generata l&quot;eccezione."
    - id: innerException
      type: System.Exception
      description: "L&quot;eccezione precedente che ha causato il <xref href=&quot;System.Data.Linq.DuplicateKeyException&quot;> </xref> eccezione."
  overload: System.Data.Linq.DuplicateKeyException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.DuplicateKeyException.Object
  id: Object
  parent: System.Data.Linq.DuplicateKeyException
  langs:
  - csharp
  name: Object
  nameWithType: DuplicateKeyException.Object
  fullName: System.Data.Linq.DuplicateKeyException.Object
  type: Property
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Ottiene l&quot;oggetto che ha causato l&quot;eccezione."
  syntax:
    content: public object Object { get; }
    return:
      type: System.Object
      description: "Oggetto che ha causato l&quot;eccezione."
  overload: System.Data.Linq.DuplicateKeyException.Object*
  exceptions: []
  platform:
  - net462
references:
- uid: System.InvalidOperationException
  isExternal: false
  name: System.InvalidOperationException
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object)
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: DuplicateKeyException(Object)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String)
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: DuplicateKeyException(Object,String)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String,System.Exception)
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: DuplicateKeyException(Object,String,Exception)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String,Exception)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Data.Linq.DuplicateKeyException.Object
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: Object
  nameWithType: DuplicateKeyException.Object
  fullName: System.Data.Linq.DuplicateKeyException.Object
- uid: System.Data.Linq.DuplicateKeyException.#ctor*
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: DuplicateKeyException
  nameWithType: DuplicateKeyException.DuplicateKeyException
- uid: System.Data.Linq.DuplicateKeyException.Object*
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: Object
  nameWithType: DuplicateKeyException.Object
