### YamlMime:ManagedReference
items:
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  id: WorkflowTerminatedEventArgs
  children:
  - System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  langs:
  - csharp
  name: WorkflowTerminatedEventArgs
  nameWithType: WorkflowTerminatedEventArgs
  fullName: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  type: Class
  summary: "Fornisce dati per la <xref href=&quot;System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated&quot;> </xref> evento."
  remarks: "> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]Un&quot;istanza del flusso di lavoro può essere terminata in tre modi: l&quot;host può chiamare <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>, <xref:System.Workflow.ComponentModel.TerminateActivity>attività può essere richiamata dall&quot;interno dell&quot;istanza del flusso di lavoro o il motore di runtime del flusso di lavoro può terminare l&quot;istanza a causa di un&quot;eccezione non gestita.</xref:System.Workflow.ComponentModel.TerminateActivity> </xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName> Quando l&quot;istanza del flusso di lavoro viene terminata, il motore di runtime del flusso di lavoro genera il <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>evento.</xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName> L&quot;host può sottoscrivere questo evento aggiungendo un gestore eventi per <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>.</xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>"
  example:
  - "The following code example demonstrates an event handler method that takes WorkflowTerminatedEventArgs as a parameter. The `OnWorkflowTerminated` method is called when the <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated> event is raised. The code uses the <xref:System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception%2A> property get the message associated with the exception that caused the workflow to terminate.  \n  \n This code example is part of the Sequential Workflow with Parameters SDK Sample from the Program.cs file. For more information, see [Sequential Workflow with Parameters](http://msdn.microsoft.com/en-us/17157f2d-8fed-4848-a386-e4efa381b66b).  \n  \n [!code-cs[WF_Samples#193](~/add/codesnippet/csharp/wf_snippets/snippets19.cs#193)]\n [!code-vb[WF_Samples#193](~/add/codesnippet/visualbasic/wf_snippets/snippets19.vb#193)]"
  syntax:
    content: >-
      [System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")]

      public class WorkflowTerminatedEventArgs : System.Workflow.Runtime.WorkflowEventArgs
  inheritance:
  - System.EventArgs
  - System.Workflow.Runtime.WorkflowEventArgs
  implements: []
  inheritedMembers:
  - System.Workflow.Runtime.WorkflowEventArgs.WorkflowInstance
  platform:
  - net462
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  id: Exception
  parent: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  langs:
  - csharp
  name: Exception
  nameWithType: WorkflowTerminatedEventArgs.Exception
  fullName: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime
  summary: "Ottiene l&quot;eccezione che ha causato la chiusura dell&quot;istanza del flusso di lavoro."
  remarks: "Quando l&quot;istanza del flusso di lavoro viene terminato a causa di un&quot;eccezione non gestita, l&quot;eccezione contiene l&quot;eccezione non gestita.       Quando l&quot;istanza del flusso di lavoro viene terminata da una chiamata dell&quot;host per <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>o da un <xref:System.Workflow.ComponentModel.TerminateActivity>eccezione di attività, contiene un <xref:System.Workflow.ComponentModel.WorkflowTerminatedException>con relativo <xref:System.Exception.Message%2A>proprietà è impostata su una descrizione del motivo della chiusura.</xref:System.Exception.Message%2A> </xref:System.Workflow.ComponentModel.WorkflowTerminatedException> </xref:System.Workflow.ComponentModel.TerminateActivity> </xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName> Se l&quot;host termina l&quot;istanza del flusso di lavoro, fornisce questa descrizione nel `string` parametro <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>.</xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName> Se l&quot;istanza del flusso di lavoro viene terminata da un oggetto <xref:System.Workflow.ComponentModel.TerminateActivity>la descrizione è fornita da <xref:System.Workflow.ComponentModel.TerminateActivity.Error%2A?displayProperty=fullName>.</xref:System.Workflow.ComponentModel.TerminateActivity.Error%2A?displayProperty=fullName> </xref:System.Workflow.ComponentModel.TerminateActivity>      > [!NOTE] > Sebbene nel caso di un <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>evento non è presente a causa di un&quot;eccezione non gestita, il motore di runtime del flusso di lavoro incapsuli una descrizione del motivo della chiusura nella <xref:System.Exception.Message%2A>proprietà di un <xref:System.Workflow.ComponentModel.WorkflowTerminatedException>, non genera necessariamente questa eccezione.</xref:System.Workflow.ComponentModel.WorkflowTerminatedException> </xref:System.Exception.Message%2A> </xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>"
  example:
  - "The following code example demonstrates how you can use the Exception property to obtain information about an exception that caused a workflow to terminate. The `OnWorkflowTerminated` method takes a <xref:System.Workflow.Runtime.WorkflowTerminatedEventArgs> as a parameter. This method is called when the <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated> event is raised. The code uses the Exception property get the message associated with the exception that caused the workflow to terminate.  \n  \n This code example is part of the Sequential Workflow with Parameters SDK Sample from the Program.cs file. For more information, see [Sequential Workflow with Parameters](http://msdn.microsoft.com/en-us/17157f2d-8fed-4848-a386-e4efa381b66b).  \n  \n [!code-cs[WF_Samples#193](~/add/codesnippet/csharp/wf_snippets/snippets19.cs#193)]\n [!code-vb[WF_Samples#193](~/add/codesnippet/visualbasic/wf_snippets/snippets19.vb#193)]"
  syntax:
    content: public Exception Exception { get; }
    return:
      type: System.Exception
      description: "Il <xref:System.Exception>che ha causato la chiusura dell&quot;istanza del flusso di lavoro.</xref:System.Exception>"
  overload: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Workflow.Runtime.WorkflowEventArgs
  isExternal: false
  name: System.Workflow.Runtime.WorkflowEventArgs
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  parent: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  isExternal: false
  name: Exception
  nameWithType: WorkflowTerminatedEventArgs.Exception
  fullName: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception*
  parent: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  isExternal: false
  name: Exception
  nameWithType: WorkflowTerminatedEventArgs.Exception
